backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'my-type'
    label: 'My type'
    folder: 'src/content/my-folder'
    create: true
    fields:
      - {
          label: 'Template Key'
          name: 'templateKey'
          widget: 'hidden'
          default: 'my-template-type'
        }
      - { label: 'Document', name: 'document', widget: 'file', required: true }
